### ISSUE TITLE
Betweener library SPI.begin(); in the begin() funtion causes conflict with audio on the audio shield

### ISSUE THREAD

**Issue by jkrame1** [jkrame1/SAIC-Converter#2] opened 2018-02-05 02:14 UTC
When the Betweener library begin(); function is called in a sketch using the STGL5000 codec controller, audio functionality is broken for the audio shield. See the "First Example of Betweener Library with Audio Shield" example for more detail.  In this example, the samples in memory still play, but no audio is produced at the output.

There is probably an easy way to handle this to avoid conflicts or automate when the SPI.begin() is needed and when it will cause problems, but I don't know the answer yet.

**Comment by kschaffer** [comment] 2018-02-05 03:04
Hmmm... OK, this sounds like something I need to catch up on, and it will take a couple of days to see if I can replicate the issue.  I remember having some odd issues with audio functionality breaking rather randomly back in the beginning of playing around with the audio shield... keep me posted if you figure stuff out, and in the mean time I will see if I can get that example running (and breaking).  thanks... 
k.

**Comment by jkrame1** [comment] 2018-02-05 03:15
Cool. I think I found where the problem lives, I just don’t know enough to fix it without breaking something else in the process. Using the begin(); function killed the audio in the two audio shield tutorials to which I tried to add Betweener library control. But in both cases everything else (LEDs, serial, trigger inputs) worked fine from the original code and the added Betweener hardware.  I don’t want to go hacking at the library if there may be an obvious answer, but dropping the one line from the .cpp fixed both frankensteins.

No rush. Thanks for taking a look when you get (find? make? create?) time.

JMK

**Comment by kschaffer** [comment] 2018-02-05 03:22
This might be really obvious and stupid, but did you experiment with order?  Like, doing the begin() function before invoking the various .enable() and whatnot in that sketch?  

I don't have an audio shield hooked up to a betweener at the moment but I should be able to test this with my breadboarded Teensy since the symptoms are at a pretty basic level.  And I'll definitely make time... having bugs to fix actually works really well to stop me from spinning my wheels on the other things I am doing.  So it's a benefit, actually!  More soon...

**Comment by jkrame1** [comment] 2018-02-05 03:31
That is a very fair question! The answer is I did try the begin() before and after the .enable(), but it was before I narrowed down what I thought the issue might be, so it was during a period of distraction and undisciplined hacking. I can only remember that I did it because I remember moving begin() from the begin of the setup() to the end, thinking that the order might be important, but knowing that I didn't have an understanding of why exactly. In other words, it would be worth examining that again now.

**Comment by kschaffer** [comment] 2018-02-05 20:45
OK, I have reproduced the bug, so I see the problem, at least.  You may have already searched on this but I am thinking maybe this thread:
https://forum.pjrc.com/threads/38584-Audio-board-with-SD-card-and-concurrent-SPI-usage
may be relevant.  Anyway what I get from it is that I need to dig a little to understand the audio library's use of interrupts ... and I might need to wrap the SPI stuff in something more intelligent, for the Betweener.  We don't want to sacrifice this functionality - having the DACs running at some reasonable rate of control while also being able to process audio at full speed.  But it looks like it might get technical.  So... I'll see where it takes me!

**Comment by kschaffer** [comment] 2018-02-09 04:37
See thread:
https://forum.pjrc.com/threads/49562-Audio-functionality-and-SPI-communication-again!-(Teensy-3-2)
for an explanation of the issue, which is now fixed by reordering the calls to SPI.begin() and SPI.setMOSI.

**Closed as completed by kschaffer** 2018-02-09 04:37 UTC
